# Default colors
[colors.primary]
background = '0x031A16'
foreground = '0x81B5AC'

# Normal colors
[colors.normal]
black = '0x1c1e1b'
red = '0x963E4C'
green = '0x4C963E'
yellow = '0xdbb651'
blue = '0x57a5e5'
magenta = '0x3E4C96'
cyan = '0x3E7996'
white = '0x81B5AC'

# Bright colors
[colors.bright]
black = '0x5b5e5a'
red = '0x963E4C'
green = '0x4C963E'
yellow = '0xdbb651'
blue = '0x57a5e5'
magenta = '0x3E4C96'
cyan = '0x3E7996'
white = '0xfff8f0'
