background              #031A16
foreground              #81B5AC
selection_background    #5b5e5a
selection_foreground    #81B5AC

cursor              #fff8f0
cursor_text_color   #0f0800

active_tab_background       #81B5AC
active_tab_foreground       #111210
inactive_tab_background     #2B685E
inactive_tab_foreground     #5b5e5a

color0  #1c1e1b
color8  #5b5e5a

color1  #963E4C
color9  #963E4C

color2  #4C963E
color10 #4C963E

color3  #dbb651
color11 #dbb651

color4  #57a5e5
color12 #57a5e5

color5  #3E4C96
color13 #3E4C96

color6  #3E7996
color14 #3E7996

color7  #f1e9dc
color15 #fff8f0
